---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vikunja
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vikunja-secret
    template:
      engineVersion: v2
      data:
        # App
        VIKUNJA_DATABASE_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        VIKUNJA_DATABASE_DATABASE: &dbName vikunja
        VIKUNJA_DATABASE_USER: &dbUser "{{ .VIKUNJA_POSTGRES_USER }}"
        VIKUNJA_DATABASE_PASSWORD: &dbPass "{{ .VIKUNJA_POSTGRES_PASS }}"
        VIKUNJA_DATABASE_SSLMODE: require
        VIKUNJA_DATABASE_TYPE: postgres
        VIKUNJA_SERVICE_JWTSECRET: "{{ .VIKUNJA_SERVICE_JWTSECRET }}"
        VIKUNJA_OAUTH_CLIENT_SECRET: "{{ .VIKUNJA_OAUTH_CLIENT_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: vikunja
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vikunja-configmap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vikunja-configmap-secret
    template:
      templateFrom:
        - configMap:
            name: vikunja-configmap
            items:
              - key: config.yml
  dataFrom:
    - extract:
        key: vikunja
