apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:xvl/yv5AGum/R1Vnev0SAfNPHwprfg==,iv:isNja7ENPcY65mUz2CDQVbhPe2q0AdRiiPKgfLKosZA=,tag:SYTWY5dbppSuA0JYRxpCdw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:K3F11kzdrnECRdTDPwG5zvJC+xMrnIcB2aebwP0U0kQ0uY+lFA==,iv:twL3NusXL+GujtOLQWOa3Hr4ZDwEj+Rez9QkhQcDqMQ=,tag:2ivTRDHmZx3WqWNdUvAgIw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:B0Z3h23rbwWeNRjYyfre,iv:7MPy6NM4Trqts4NnaLJFrIFsyEX0TAC4MxgLYeL1+tc=,tag:0hfA3/J76uHZfnMPSlIXdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vuvrs7evuks8zjl949dl2mcn4elxz0578cs03tnc63lt5aej49xqv92j8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4d0pMK0ltWWx1cm5HUnAr
            NVJtMXErRWJnUzNSZ05qY1ZnbGJ2eW9BckU4CjJQQVkxZVVtZWFsR2lFZGFROXgx
            amExTCtVMC9rck9CNTVtVHVVQithMk0KLS0tIDFoRnRVdmUzbkwwWkdkdkg2bU8r
            cDU2L0Q0d2owOXVJL3VZZnJlSTBMUGMK7TNEI6XW0bKkYmE2+ovBHyz2HjGeASgm
            qFqpyqRh6ogSc5jbkJ3hGnJ4ZePnIOL0vZNFG+w0k/PKq04pYxu2YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T21:15:17Z"
    mac: ENC[AES256_GCM,data:Yank67XelVinzR9EMM1flMN/mziADl26OGm10MKWbPSXxFnrkxerqEisbu2doLZ/qgY65QLdRsM3pQPs2FFYQVaGqAB6pe69m65XOZ80vRHEFdBhrAg8ceEsJMU2LL8ait2bAvds1KwiV2Rrjx6FLPuA2zcNMe+8mHAbEBs8m2A=,iv:0fZp5io1XnUrSbsBoi3US5AovfhErDP8+fwUu2wDkv4=,tag:AZLFeka+kUfr6b8imtydSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
