---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-secrets
    template:
      engineVersion: v2
      data:
        # Authentik
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        AUTHENTIK_REDIS__HOST: authentik-redis.security.svc.cluster.local
        AUTHENTIK_POSTGRESQL__USER: "{{ .AUTHENTIK_PG_USER }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .AUTHENTIK_PG_PASS }}"
        AUTHENTIK_POSTGRESQL__HOST: postgres16-rw.database.svc.cluster.local
        AUTHENTIK_POSTGRESQL__NAME: &dbname authentik
        # AUTHENTIK_EMAIL__USERNAME: "{{ .AUTHENTIK_EMAIL__USERNAME }}"
        # AUTHENTIK_EMAIL__PASSWORD: "{{ .AUTHENTIK_EMAIL__PASSWORD }}"
        AUTHENTIK_BOOTSTRAP_EMAIL: "{{ .AUTHENTIK_BOOTSTRAP_EMAIL }}"
        AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .AUTHENTIK_BOOTSTRAP_PASSWORD }}"
        # AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .AUTHENTIK_BOOTSTRAP_TOKEN }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .AUTHENTIK_PG_USER }}"
        INIT_POSTGRES_PASS: "{{ .AUTHENTIK_PG_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # GEOLITE
        GEOIP_ACCOUNT_ID: "{{ .GEOIP_ACCOUNT_ID }}"
        GEOLITE_LICENSE_KEY: "{{ .GEOLITE_LICENSE_KEY }}"
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: authentik-bootstrap
    - extract:
        key: cloudnative-pg
    - extract:
        key: geolite
