apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:LeCy8OIiGL/XllXwFMy/5KtwS15hNI6+3YM6NhIq5mb6lIvMcSHPyG1eLvMjykpOgljqJykFU7OyjzAF,iv:lJTllZyx+xFwOn3anf2SD8MTIqCOeyymRYPfA5KtcxA=,tag:UjwqYGpVMVbHMYvR8hNeKQ==,type:str]
    username: ENC[AES256_GCM,data:IaAcsrQ=,iv:bXk+Z+UiN6HwcN3G86UvGsJbqVK3DYq7sFT23wlcTzY=,tag:DPAYqPXfSKxBy2ttPNcFLA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16d3834k4ae5mcwaksdkwk6w6w0xlu2apvgmazpx2qa6x4e7ydcnsy3gh9u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYUphd0w1bG8rdmZ0MitP
            WTRHa1ZJenMzdFRaS0dSTzZWall6SGZ0K2lBClpyNDZUbEdZcE5BUkZnbVNzOU1J
            MzlwOVM2Q0JQQ3VUR3BsMEtBeUNtb0EKLS0tIEg1NFE3MnAvb211RzdtSnY5TnNa
            eGQyd2NwYU9nRTdPK0wwVDZIN2krSHcKI6/8q3Uo2SSCFJLuGJcW6FYaCCKaWg+O
            U3ZeFv/6M1ZxnN9/Fx3eCGARBuzbgw4LGNMWVmHSbSK50GfsyOE/tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-01T06:58:37Z"
    mac: ENC[AES256_GCM,data:3M+aEbYDLT2YAghQv6DMpDMK4NAG3k7l4Z/na1QS2+i9n6/Dk6HEWKB0eEdVh5+aE+ufL0q+bEq9Jf03f+EXl0QMlOl6erLnxps7Mva7aiTs8LVh0X/hUu5vmMKUUNYLVgrhL5o4zoqHFw3seuZrtPnIYBaNvsoDmkce36NU/1Y=,iv:v7466hBNAMUSBkjTzFnix/KtYC16n9tbAfkkvmrKuEM=,tag:iRdUItubAIOf5W5mAkfQAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
