---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: &ns vpn
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://angelnu.github.io/helm-charts/
      chart: pod-gateway
      version: 6.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system

  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.8.1@sha256:690b6365728fe9012ad4cdfca38334992664596513dca187d1b93d2025205776

    env:
      TZ: "American/Chicago"

    routed_namespaces:
      - download

    publicPorts:
      - hostname: qbittorrent # hostname assigned to the pod
        IP: 10 # must be an integer between 2 and VXLAN_GATEWAY_FIRST_DYNAMIC_IP (20 by default)
        ports:
          - type: udp
            port: 62204
          - type: tcp
            port: 62204

    # Default VPN_VXLAN DNS
    DNS: 172.16.0.1

    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.0.0.0/8 192.168.0.0/16 172.16.0.0/12"
      # tun0 for openvpn, wg0 for wireguard
      VPN_INTERFACE: wg0
      # VXLAN_IP_NETWORK: ${WG_VXLAN_CIDR}
      # Prevent non VPN traffic to leave the gateway
      VPN_BLOCK_OTHER_TRAFFIC: false
      # If VPN_BLOCK_OTHER_TRAFFIC is true, allow VPN traffic over this port
      VPN_TRAFFIC_PORT: 51820
      # Traffic to these IPs will be send through the K8S gateway
      # change if your K8S cluster or home network uses a different CIDR
      VPN_LOCAL_CIDRS: "10.0.0.0/8 192.168.0.0/16 172.16.0.0/12"

    webhook:
      image:
        repository: ghcr.io/seandonohoo/gateway-admision-controller
        tag: dev@sha256:538fdaf5b6373ca9bb7da31d0180d42e3f990b9889e2819ff8376e94cd8faf5c
      gatewayDefault: false
      gatewayLabel: setGateway
      gatewayAnnotation: setGateway
      namespaceSelector:
        label: "routed-gateway"

    livenessProbe:
      exec:
        command:
          - sh
          - -c
          - if [ $(curl -s https://am.i.mullvad.net/country) = '${VPN_COUNTRY}' ]; then exit 0; else exit $?; fi
      initialDelaySeconds: 30
      periodSeconds: 60
      failureThreshold: 1

    nodeSelector:
      kubernetes.io/hostname: "k3s2"

    addons:
      netshoot:
        enabled: true

      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: docker.io/qmcgaw/gluetun
            tag: latest@sha256:1b6962746d67d33b7a0791f648c8789bec181179d50005dcc80599877cad52e3

        env:
          - name: VPN_SERVICE_PROVIDER
            value: custom
          - name: VPN_TYPE
            value: wireguard
          - name: VPN_INTERFACE
            value: wg0
          - name: FIREWALL
            value: "off"
          - name: DOT
            value: "off"
          - name: HEALTH_TARGET_ADDRESS
            value: "mullvad.net:443"

        envFrom:
          - secretRef:
              name: vpnconfig
        securityContext:
          capabilities:
            add:
              - NET_ADMIN

        resources:
          requests:
            cpu: "0.001"
            memory: 128Mi
          limits:
            memory: 2Gi

        networkPolicy:
          enabled: true

          egress:
            - to:
                - ipBlock:
                    cidr: 0.0.0.0/0
              ports:
                - port: 51820
                  protocol: UDP
                - port: 51820
                  protocol: TCP
                - port: 53
                  protocol: UDP
            - to:
                # Allow traffic within K8S - change if your K8S cluster uses a different CIDR
                - ipBlock:
                    cidr: "10.0.0.0/8"
                - ipBlock:
                    cidr: "10.0.0.0/8"
                - namespaceSelector: {}
