apiVersion: v1
kind: Secret
metadata:
    name: vpnconfig
    namespace: vpn
type: Opaque
stringData:
    #ENC[AES256_GCM,data:8/KNRB7yol2YgWQ=,iv:BZEah4Y5v0Bbi02DNLrlxBGFkXkkFD+RVstb8so0n78=,tag:o3Il6wRgHWK8E60xQfOY8Q==,type:comment]
    #ENC[AES256_GCM,data:kpi56w7pb7orPuStuhmwEpN9xVyqmH5a7N+S5hR74w7YG/Xh+NWmosBzjjzx,iv:6/0YBYinE12rmb3PQCneYiAgauRNT7Ag0ZCPLt/Q9cw=,tag:DQFide1eBgeimCqbvlOuEQ==,type:comment]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:MGj0QuSbXk1f2CS2Ag5B7g8FPi2koIKEcOaJjtefxCf5AVf0tPj20Bq7p2A=,iv:J3As7z8hIChvkdLoCDsFK0y8Ko+BIZ09q6nxiBzgcz0=,tag:h+CpZnyiYRguIp/BQ8QAjg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:TqUOYyLYSUhFpKU/mS6IWw==,iv:F4/NKvS2hWksKrWJo8NnV0N5F4bl0+lxXe6R5Wp5vyg=,tag:rFRvXS4cS9tBRuJTeh21Zw==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:1wy7z/oOpXVNnn0ZGtITRpfHUIfAMdLOTlFXLgd6x0/SVjJKZl9+BDPE7Z4=,iv:rMaup6zpDs6FbJmycqOIa8fCWZHGwsZ2weRQGhv9WwA=,tag:4sMsdgPJ6hlhqLm0LbzISA==,type:str]
    VPN_ENDPOINT_IP: ENC[AES256_GCM,data:ElKg77dQoW2+V5zNAQ==,iv:FDMeAWon4gZKUIDntBASMPFUtbz0Bjna8eFcCPsjm9A=,tag:EA98WU7gZM38OH+45L3y9A==,type:str]
    VPN_ENDPOINT_PORT: ENC[AES256_GCM,data:MnwvrsM=,iv:hDkHseEoc0frcl4jNtaCsNzeywggzV6xItQSRzVgEbY=,tag:h/IKW382OjKAmiVXZhEYCA==,type:str]
    #ENC[AES256_GCM,data:PBWKpW55iA==,iv:c8hxyONrmmecPH7KkWy5AJ8eDCvqP4EFj5VZleYMs5c=,tag:YlFdkBER5ghE5Co9VkDuRA==,type:comment]
    #ENC[AES256_GCM,data:NvbuWgVlGdkc6prJF2L7Mw3tWP52p6qavBFMme0Jt3fkc/iRjDhNAtIwNLwqlzAz7MrrN7Bb7fmmyYuWQNp6McD6VBg=,iv:N7OFNTxqWwdgLzuCWPV7h2pP8LwGIY4I9YUa8hu8AbA=,tag:aKgUkExoxPSjx34baV6E9w==,type:comment]
    #ENC[AES256_GCM,data:Fg4issSUROqDlH2rEsa3BXuoUDgKRZZyxQ4QgXoHNH3Y,iv:/1aO4Fqtftl3t9T8Ireq5dvZSogqiklYzVzMSOLVzcs=,tag:t7mL9TrPonRJWnjAxyWpQw==,type:comment]
    #ENC[AES256_GCM,data:vOe2XCyfZQk4IP2lNmrvEmnNAXiUpgNNpXJdpYj5GwxAL1UpYzJLCm/BjbE6f3ZCKDhECrx5K0cnLsHoX/vL4XmsWw==,iv:mO1zbjCjCqD4gDxdW1hhm82FXyepyF+CnVuMnkFa85M=,tag:HsX8Po/Cdy6tY4aNomGp+w==,type:comment]
    #ENC[AES256_GCM,data:PMiraNNUFey5DXyPLI92MDGuMdfJ7Gs415EBUyE=,iv:uD1N4gGkHOAYy2rE9OIMsrNuUr1r77WvTGD13nN7bwg=,tag:4D5+xo8y+XdG8ibTSMl98A==,type:comment]
    #ENC[AES256_GCM,data:7LKPx9chjjyDLLZ4k0bKcu5zEqC+7zdXepciKgbY7N8=,iv:hd0INLMXHG+ThuoGPAcPV+46D+bGxnV5JjrrAmAXHaQ=,tag:PGvi5AgWoZ3qMN5vJE/DzA==,type:comment]
    #ENC[AES256_GCM,data:gqiW5IJRbgHl6KJHoqtwoFoZDBn2YiljYNcz,iv:Y/pdQlp/u9tj/vNtdDE5i04jobaQ69CsZRg/ZSCibH4=,tag:aPz6ud0QcapIIgYi1azfgA==,type:comment]
    SECRET_VPN_BT_FORWARD_PORT_1: ENC[AES256_GCM,data:QacDer8=,iv:bc7H8n1HbWiIVc+/PJLMdGYVGKdjnW9GWHt2ZtQZPEs=,tag:Cg7OBTfh2hFf1SyduFfcOg==,type:str]
    VPN_COUNTRY: ENC[AES256_GCM,data:N2LAjQSbP1mGoWyMvg==,iv:kZVOHZrP+tsmH4ZGQpdJbEJQ/+Rt10z0BefqSbo0cW0=,tag:yRCA5+0Sn2QLi6ShM1+vbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16d3834k4ae5mcwaksdkwk6w6w0xlu2apvgmazpx2qa6x4e7ydcnsy3gh9u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZUk1RjVKbWtpajUvcHdB
            RUQ5SFJQU05CazFBR1VqdHJOaFpIZDdJWndrCkhkYmhjOEd3UEI3NENzT1loYjlW
            Rk10elZObGNPaWVFUEF5emZ6NjZEME0KLS0tIFAvNFVKRFVtOGF6cW1TcDZWKzNo
            T1V1RmhFaGtoaUY0QjBqbGVTeGxmVWsK5RDAK/D8OFEnFzx0Y/vYXqYSdPW8Djd4
            jqwqCdEMviDAs1sconVXgUyC8s1YufFa8jwiaQl6hkssyC77khE1sw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vuvrs7evuks8zjl949dl2mcn4elxz0578cs03tnc63lt5aej49xqv92j8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBK0djYU8rOW90bXZMdkhN
            K1BhTDNHTitLWDEwZGZRK2Q5Nk5zOEsxVjNrCm5hdDFNeG8zS05ZTG9mQVY3cHZW
            VG01dHEwNTN5NGVRMjhVbDJVUFJBS00KLS0tIDNqOEpmejNMb0lUTkN1Z1Q0dHZy
            V1ZRYTl3dTAyQURVVG9FUjdMRzRSY3cKAcM1gZy38/zZax26J1OkQBPQKFYA1uuH
            +IDlFk6V29Q5tJbHFreSxwi+PUAUC3Yj9L7m+KJOwqNzJUOVhe7rKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-30T03:45:24Z"
    mac: ENC[AES256_GCM,data:k5cWelxj+DNi/dUWgn9pbkfpJLN//DR3V4pF4pc76N08bcU8pNHLTklEPSCYcPWL8svIDieNV8ZGOwVN7jmLYAPbm6mC7So+r7erB7QqQJqJltleiQ2MQhIOSLwq+4CEP9a4Vdnp2DvS27KHdApotxFt701j6ZHfIiTI50O/waM=,iv:5Ip+n/JEZjdy0ixT2w0PADyS9zeY7lvebbxvoiawINU=,tag:SdAgVzr8+2LdEsNmDAgueQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
