---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: hass
spec:
  staticConfigs:
    - targets:
        - "ha.${SECRET_DOMAIN}"
  metricsPath: /api/metrics
  authorization:
    credentials: "${SECRET_HASS_TOKEN}"
