apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:zO957jzMfUx1uRUCBx9W,iv:IhTi3MFJlTfNzVUWj5kH+6uAAMdPYGF+tecvbxaItjs=,tag:guajYNZohqATbs/SfIoFUQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:I3Ze9jSafY6zFA==,iv:t8RdgQFa7zT0KepTH/5zk7uYuKas/P0xD1KiL6G2r6M=,tag:1+5aBCwyQ1qC0YLDJHU8TQ==,type:str]
    OLD_SECRET_DOMAIN: ENC[AES256_GCM,data:SoAtOrMuIMJQJs/6,iv:PLzn/E7OHsBWfRE/nVUdnD0TvwKHzCVlFrdEDWwDR8o=,tag:r8r3pWiZlfYTg3X8B3jS9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16d3834k4ae5mcwaksdkwk6w6w0xlu2apvgmazpx2qa6x4e7ydcnsy3gh9u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdWR5eGl2ZVE3QjYrbTdQ
            R2NRcVlSMFVGdWhnb0JTYkRJbEJQcWNBZUhjClorZFFhK1FnQmNBRzhKczF0aEFI
            OTdwS0NpeElPRGpWc1BxMTVDa0Rjd1EKLS0tIE9nU3VmSE1HRGRsMUUvcmpNU3hh
            SitWeVFQSjl3dTQwU3NoSHRGV1FnUXMKnoXSLdqDvv+Pa4dlFrJ0D4GkI5RC6jEk
            7xe2edodbom8+YePUMB2kMbQZqsGb4V2zysEx+/kxA8P2d9aw9YBmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T02:23:38Z"
    mac: ENC[AES256_GCM,data:/C5EWzrwB0m67a06529Bf51AMxTxsdudDTc3ScKlzLKrLpOQf6HfVu2OqGuG8rv4TfLwCv3ge4rDmDYIZMCnsXoezVNGuzEb40ZjLkr3Y3U6DLQ51JGIdgw5JL9LAxDWXojSfeLdZ18MXmH8V5W0Kpw4eV63+BFgrwJKaJ/6odc=,iv:TTKLNqT3Rb+y96f8laULYEx1u0I1LRRHa/afkllV+Zo=,tag:t/v977gzKGYf5I9e1sVIzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
