apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:z3ur1kztnExH86r0,iv:Pok7wFkEK/qoNrEK8x3vPeYFOXfvDA5fkZiGoAe66yM=,tag:+QqR9qUYlXZJ9whmiGvNNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16d3834k4ae5mcwaksdkwk6w6w0xlu2apvgmazpx2qa6x4e7ydcnsy3gh9u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvT1Fpby9tUXpmSmVwa3pR
            VnpxU0hCcytNU2h5aFVEUDZMREF4dnQ5a2tVClU5SHpjMHlMenUrdU9iTHJJLzRv
            TDhiSkhhMER6d2hTakdiek53bk1JaDgKLS0tIHVmMnlOci9uM01qMXJnbUd6ZzFF
            SE1rdVEvMU5WWWFLZmRVR0NRUGVhd3cKfrZ2VDISkkLbQNgT8dOP17xVfBIa3bXN
            OO/Cg+llckaxDVqU0M7aZpF/PKUajgCdWSuLfsae6rVXAoKPEs4dUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-01T06:58:28Z"
    mac: ENC[AES256_GCM,data:j8dsNDHgvYCTspZkwlsMrpWgDFYjWljv3qBqTBED7k3UK1XIx+/W/BL5hplpI6EGnQNbVcibKX6FmcaoZYiQVqzygSvn/oX2ObtOqMnjhb1Z16xi1V72ANbH9vv5Hv8epO6H2NFmkMi1slHoD6HV7W+9CPzt0dRzLyOfN8PNbMc=,iv:hGYEowTEae7K3VJaGt0Ymw+vQ1ZTMX9sboE44vZP7eQ=,tag:qqza3mMGWjOb1jf9MsPWSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
